INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-01', 'Achats','achats');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-02', 'Assistant(e)','assistante');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-03', 'Banque','banque');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-04', 'Bureautique - PAO/CAO','bureautique, pao, cao');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-05', 'Changement','changement');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-06', 'Coaching','coaching');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-07', 'Commercial - Ventes','commercial, ventes');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-08', 'Communication','communication');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-09', 'Comptabilité - Fiscalité','comptabilite, fiscalite');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-10', 'Contrôle de gestion','controle, gestion');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-11', 'Création d’entreprise','creation, dentreprise');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-12', 'Direction de l''entreprise','direction, entreprise');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-13', 'Droit des affaires','droit, affaires');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-14', 'Droit social','droit, social');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-15', 'Développement personnel','developpement, personnel');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-16', 'Efficacité professionnelle','efficacite, professionnelle');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-17', 'Finance - Trésorerie','finance, tresorerie');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-18', 'Formation de formateurs','formation, formateurs');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-19', 'Formations en anglais','formations, anglais');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-20', 'Gestion du temps','gestion, temps');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-21', 'IA - Digital','ia, digital');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-22', 'Immo','immo');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-23', 'Informatique SI','informatique');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-24', 'Innovation créativité','innovation, creativite');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-25', 'International','international');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-26', 'Logistique - Supply chain','logistique, supply, chain');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-27', 'Management','management');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-28', 'Marketing','marketing');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-29', 'Organisation - Audit','organisation, audit');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-30', 'Paie/Admin.','paie, admin');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-31', 'Production - Lean','production, lean');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-32', 'Projet','projet');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-33', 'QVT','qvt');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-34', 'Qualité-Santé-Sécurité-Env','qualite, sante, securite, env');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-35', 'RSE - Dev. Durable','rse, dev, durable');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-36', 'Relation client','relation, client');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-37', 'Ressources humaines','ressources, humaines');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-38', 'Secteur public','secteur, public');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-39', 'Soft skills','soft, skills');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-40', 'Travail à distance','travail, distance');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation,MotsCles) VALUES ('CEGOS_DomaineF-41', 'Web','web');
