INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-01-01', 'COURSERA_DomaineF-01', 'Computer Security and Networks', 'computer, security, networks');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-01-02', 'COURSERA_DomaineF-01', 'Design and Product', 'design, product');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-01-03', 'COURSERA_DomaineF-01', 'Software Development', 'software, development');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-01-04', 'COURSERA_DomaineF-01', 'Algorithms', 'algorithms');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-01-05', 'COURSERA_DomaineF-01', 'Mobile and Web Development', 'mobile, web, development');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-02-01', 'COURSERA_DomaineF-02', 'Data Analysis', 'data, analysis');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-02-02', 'COURSERA_DomaineF-02', 'Machine Learning', 'machine, learning');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-02-03', 'COURSERA_DomaineF-02', 'Probability and Statistics', 'probability, statistics');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-03-01', 'COURSERA_DomaineF-03', 'Leadership and Management', 'leadership, management');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-03-02', 'COURSERA_DomaineF-03', 'Marketing', 'marketing');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-03-03', 'COURSERA_DomaineF-03', 'Business Essentials', 'business, essentials');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-03-04', 'COURSERA_DomaineF-03', 'Business Strategy', 'business, strategy');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-03-05', 'COURSERA_DomaineF-03', 'Finance', 'finance');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-03-06', 'COURSERA_DomaineF-03', 'Entrepreneurship', 'entrepreneurship');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-04-01', 'COURSERA_DomaineF-04', 'Support and Operations', 'support, operations');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-04-02', 'COURSERA_DomaineF-04', 'Cloud Computing', 'cloud, computing');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-04-03', 'COURSERA_DomaineF-04', 'Data Management', 'data, management');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-04-04', 'COURSERA_DomaineF-04', 'Security', 'security');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-04-05', 'COURSERA_DomaineF-04', 'Networking', 'networking');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-05-01', 'COURSERA_DomaineF-05', 'History', 'history');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-05-02', 'COURSERA_DomaineF-05', 'Music and Art', 'music, art');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-06-01', 'COURSERA_DomaineF-06', 'Personal Development', 'personal, development');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-07-01', 'COURSERA_DomaineF-07', 'Basic Science', 'basic, science');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-07-02', 'COURSERA_DomaineF-07', 'Psychology', 'psychology');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-07-03', 'COURSERA_DomaineF-07', 'Health Informatics', 'health, informatics');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-07-04', 'COURSERA_DomaineF-07', 'Healthcare Management', 'healthcare, management');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-07-05', 'COURSERA_DomaineF-07', 'Patient Care', 'patient, care');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-07-06', 'COURSERA_DomaineF-07', 'Public Health', 'public, health');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-07-07', 'COURSERA_DomaineF-07', 'Nutrition', 'nutrition');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-07-08', 'COURSERA_DomaineF-07', 'Research', 'research');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-08-01', 'COURSERA_DomaineF-08', 'Learning English', 'learning, english');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-09-01', 'COURSERA_DomaineF-09', 'Governance and Society', 'governance, society');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-09-02', 'COURSERA_DomaineF-09', 'Economics', 'economics');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-09-03', 'COURSERA_DomaineF-09', 'Education', 'education');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-10-01', 'COURSERA_DomaineF-10', 'Math and Logic', 'math, logic');
INSERT INTO SousDomaineFormation (RefSousDomaine, RefDomaine, SousDomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-11-01', 'COURSERA_DomaineF-11', 'Electrical Engineering', 'electrical, engineering');
