INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-01', 'Computer Science', 'computer, science');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-02', 'Data Science', 'data, science');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-03', 'Business', 'business');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-04', 'Information Technology', 'information, technology');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-05', 'Arts and Humanities', 'arts, humanities');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-06', 'Personal Development', 'personal, development');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-07', 'Health', 'health');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-08', 'Language Learning', 'language, learning');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-09', 'Social Sciences', 'social, sciences');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-10', 'Math and Logic', 'math, logic');
INSERT INTO DomaineFormation (RefDomaine, DomaineDeFormation, MotsCles) VALUES ('COURSERA_DomaineF-11', 'Physical Science and Engineering', 'physical, science, engineering');
