INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-01-01', 'Web Development', 'UDEMY_DomaineF-01');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-01-02', 'Data Science', 'UDEMY_DomaineF-01');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-01-03', 'Mobile Development', 'UDEMY_DomaineF-01');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-01-04', 'Programming Languages', 'UDEMY_DomaineF-01');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-01-05', 'Game Development', 'UDEMY_DomaineF-01');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-01-06', 'Database Design et Development', 'UDEMY_DomaineF-01');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-01-07', 'Software Testing', 'UDEMY_DomaineF-01');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-01-08', 'Software Engineering', 'UDEMY_DomaineF-01');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-01-09', 'Software Development Tools', 'UDEMY_DomaineF-01');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-01-10', 'No-Code Development', 'UDEMY_DomaineF-01');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-01', 'Entrepreneurship', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-02', 'Communication', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-03', 'Management', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-04', 'Sales', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-05', 'Business Strategy', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-06', 'Operations', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-07', 'Project Management', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-08', 'Business Law', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-09', 'Business Analytics et Intelligence', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-10', 'Human Resources', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-11', 'Industry', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-12', 'E-Commerce', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-13', 'Media', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-14', 'Real Estate', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-02-15', 'Other Business', 'UDEMY_DomaineF-02');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-03-01', 'Accounting et Bookkeeping', 'UDEMY_DomaineF-03');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-03-02', 'Compliance', 'UDEMY_DomaineF-03');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-03-03', 'Cryptocurrency et Blockchain', 'UDEMY_DomaineF-03');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-03-04', 'Economics', 'UDEMY_DomaineF-03');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-03-05', 'Finance', 'UDEMY_DomaineF-03');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-03-06', 'Finance Cert et Exam Prep', 'UDEMY_DomaineF-03');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-03-07', 'Financial Modeling et Analysis', 'UDEMY_DomaineF-03');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-03-08', 'Investing et Trading', 'UDEMY_DomaineF-03');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-03-09', 'Money Management Tools', 'UDEMY_DomaineF-03');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-03-10', 'Taxes', 'UDEMY_DomaineF-03');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-03-11', 'Other Finance et Accounting', 'UDEMY_DomaineF-03');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-04-01', 'IT Certifications', 'UDEMY_DomaineF-04');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-04-02', 'Network et Security', 'UDEMY_DomaineF-04');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-04-03', 'Hardware', 'UDEMY_DomaineF-04');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-04-04', 'Operating Systems et Servers', 'UDEMY_DomaineF-04');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-04-05', 'Other IT et Software', 'UDEMY_DomaineF-04');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-05-01', 'Microsoft', 'UDEMY_DomaineF-05');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-05-02', 'Apple', 'UDEMY_DomaineF-05');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-05-03', 'Google', 'UDEMY_DomaineF-05');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-05-04', 'SAP', 'UDEMY_DomaineF-05');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-05-05', 'Oracle', 'UDEMY_DomaineF-05');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-05-06', 'Other Office Productivity', 'UDEMY_DomaineF-05');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-01', 'Personal Transformation', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-02', 'Personal Productivity', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-03', 'Leadership', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-04', 'Career Development', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-05', 'Parenting et Relationships', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-06', 'Happiness', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-07', 'Religion et Spirituality', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-08', 'Personal Brand Building', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-09', 'Creativity', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-10', 'Influence', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-11', 'Self Esteem et Confidence', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-12', 'Stress Management', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-13', 'Memory et Study Skills', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-14', 'Motivation', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-06-15', 'Other Personal Development', 'UDEMY_DomaineF-06');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-07-01', 'Web Design', 'UDEMY_DomaineF-07');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-07-02', 'Graphic Design et Illustration', 'UDEMY_DomaineF-07');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-07-03', 'Design Tools', 'UDEMY_DomaineF-07');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-07-04', 'User Experience Design', 'UDEMY_DomaineF-07');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-07-05', 'Game Design', 'UDEMY_DomaineF-07');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-07-06', '3D et Animation', 'UDEMY_DomaineF-07');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-07-07', 'Fashion Design', 'UDEMY_DomaineF-07');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-07-08', 'Architectural Design', 'UDEMY_DomaineF-07');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-07-09', 'Interior Design', 'UDEMY_DomaineF-07');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-07-10', 'Other Design', 'UDEMY_DomaineF-07');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-01', 'Digital Marketing', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-02', 'Search Engine Optimization', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-03', 'Social Media Marketing', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-04', 'Branding', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-05', 'Marketing Fundamentals', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-06', 'Marketing Analytics et Automation', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-07', 'Public Relations', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-08', 'Paid Advertising', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-09', 'Video et Mobile Marketing', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-10', 'Content Marketing', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-11', 'Growth Hacking', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-12', 'Affiliate Marketing', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-13', 'Product Marketing', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-08-14', 'Other Marketing', 'UDEMY_DomaineF-08');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-09-01', 'Esoteric Practices', 'UDEMY_DomaineF-09');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-09-02', 'Arts et Crafts', 'UDEMY_DomaineF-09');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-09-03', 'Beauty et Makeup', 'UDEMY_DomaineF-09');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-09-04', 'Esoteric Practices', 'UDEMY_DomaineF-09');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-09-05', 'Food et Beverage', 'UDEMY_DomaineF-09');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-09-06', 'Gaming', 'UDEMY_DomaineF-09');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-09-07', 'Home Improvement et Gardening', 'UDEMY_DomaineF-09');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-09-08', 'Pet Care et Training', 'UDEMY_DomaineF-09');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-09-09', 'Travel', 'UDEMY_DomaineF-09');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-09-10', 'Other Lifestyle', 'UDEMY_DomaineF-09');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-10-01', 'Digital Photography', 'UDEMY_DomaineF-10');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-10-02', 'Photography', 'UDEMY_DomaineF-10');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-10-03', 'Portrait Photography', 'UDEMY_DomaineF-10');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-10-04', 'Photography Tools', 'UDEMY_DomaineF-10');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-10-05', 'Commercial Photography', 'UDEMY_DomaineF-10');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-10-06', 'Video Design', 'UDEMY_DomaineF-10');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-10-07', 'Other Photography et Video', 'UDEMY_DomaineF-10');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-11-01', 'Fitness', 'UDEMY_DomaineF-11');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-11-02', 'General Health', 'UDEMY_DomaineF-11');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-11-03', 'Sports', 'UDEMY_DomaineF-11');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-11-04', 'Nutrition et Diet', 'UDEMY_DomaineF-11');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-11-05', 'Yoga', 'UDEMY_DomaineF-11');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-11-06', 'Mental Health', 'UDEMY_DomaineF-11');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-11-07', 'Martial Arts et Self Defense', 'UDEMY_DomaineF-11');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-11-08', 'Safety et First Aid', 'UDEMY_DomaineF-11');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-11-09', 'Dance', 'UDEMY_DomaineF-11');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-11-10', 'Meditation', 'UDEMY_DomaineF-11');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-11-11', 'Other Health et Fitness', 'UDEMY_DomaineF-11');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-12-01', 'Instruments', 'UDEMY_DomaineF-12');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-12-02', 'Music Production', 'UDEMY_DomaineF-12');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-12-03', 'Music Fundamentals', 'UDEMY_DomaineF-12');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-12-04', 'Vocal', 'UDEMY_DomaineF-12');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-12-05', 'Music Techniques', 'UDEMY_DomaineF-12');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-12-06', 'Music Software', 'UDEMY_DomaineF-12');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-12-07', 'Other Music', 'UDEMY_DomaineF-12');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-13-01', 'Engineering', 'UDEMY_DomaineF-13');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-13-02', 'Humanities', 'UDEMY_DomaineF-13');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-13-03', 'Math', 'UDEMY_DomaineF-13');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-13-04', 'Science', 'UDEMY_DomaineF-13');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-13-05', 'Online Education', 'UDEMY_DomaineF-13');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-13-06', 'Social Science', 'UDEMY_DomaineF-13');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-13-07', 'Language Learning', 'UDEMY_DomaineF-13');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-13-08', 'Teacher Training', 'UDEMY_DomaineF-13');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-13-09', 'Test Prep', 'UDEMY_DomaineF-13');
INSERT INTO SousDomaineFormation (RefSousDomaine, SousDomaineDeFormation, RefDomaine) VALUES ('UDEMY_DomaineF-13-10', 'Other Teaching et Academics', 'UDEMY_DomaineF-13');
